import type { User, Post, Comment, Notification, Report } from "./types"

export const mockUsers: Record<string, User> = {
  user1: {
    id: "user1",
      name: "Yoga Pros",
    avatar: "https://images.unsplash.com/photo-1633722715463-d30f4f325e24?w=400&h=400&fit=crop",
    bio: "Chuyên gia sức khỏe, yêu thích yoga và dinh dưỡng",
    followers: 1250,
    following: 342,
    isFollowing: false,
  },
  user2: {
    id: "user2",
    name: "Linh Vy",
    avatar: "/workout.png",
    bio: "Huấn luyện viên fitness, tư vấn lối sống lành mạnh",
    followers: 2340,
    following: 156,
    isFollowing: false,
  },
  user3: {
    id: "user3",
    name: "Nguyễn Nam",
    avatar: "/harddata/avt/BS-Ho-Thanh-Lich-duoi-1mb.jpg",
    bio: "Bác sĩ tim mạch, chia sẻ kiến thức y tế",
    followers: 3120,
    following: 98,
    isFollowing: false,
  },
  user4: {
    id: "user4",
    name: "Minh Anh",
    avatar: "/vegeta.png",
    bio: "Dinh dưỡng sĩ, hỗ trợ chế độ ăn uống khoa học",
    followers: 1890,
    following: 234,
    isFollowing: false,
  },
  user5: {
    id: "user5",
    name: "Phạm Minh",
    avatar: "/harddata/avt/768x1152.jpeg",
    bio: "Bác sĩ đa khoa, chuyên gia tư vấn sức khỏe tổng quát",
    followers: 4250,
    following: 180,
    isFollowing: false,
  },
  user6: {
    id: "user6",
    name: "Linh Phan",
    avatar: "/harddata/avt/z5463959601833_0e49fa867f8cbc63944708e3e93d6fc1-1.jpg",
    bio: "Bác sĩ nhi khoa, yêu thích chăm sóc sức khỏe trẻ em",
    followers: 3890,
    following: 215,
    isFollowing: false,
  },
  user7: {
    id: "user7",
    name: "Dr Azumi",
    avatar: "/harddata/avt/azumi.jpg",
    bio: "Chuyên gia dinh dưỡng & sức khỏe tinh thần",
    followers: 2670,
    following: 298,
    isFollowing: false,
  },
  user8: {
    id: "user8",
    name: "Buddy & Friends",
    avatar: "/harddata/avt/beagle.jpg",
    bio: "Trang chia sẻ về sức khỏe và chăm sóc thú cưng",
    followers: 5120,
    following: 142,
    isFollowing: false,
  },
  user9: {
    id: "user9",
    name: "Tommy & Max",
    avatar: "/harddata/avt/teenage-boy-with-furry-dog-on-leafy-trail-in-the-woods-on-fall-day-cavan-images.jpg",
    bio: "Yêu động vật, yêu thiên nhiên - sống khỏe mỗi ngày",
    followers: 1980,
    following: 367,
    isFollowing: false,
  },
  currentUser: {
    id: "current",
    name: "Tuấn Hiệp",
    avatar: "https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=400&fit=crop",
    bio: "Yêu sức khỏe, yêu cuộc sống",
    followers: 450,
    following: 328,
  },
}

export const mockPosts: Post[] = [
  {
    id: "post1",
    author: mockUsers.user1,
    caption:
      "5 bài tập yoga tuyệt vời mà bạn có thể làm buổi sáng để bắt đầu ngày mới. Yoga không chỉ giúp tăng tính linh hoạt mà còn giảm stress và cải thiện tinh thần. Hãy thử ngay hôm nay! 🧘‍♀️",
    image: "/yoga-morning-exercises.jpg",
    likes: 1234,
    comments: 89,
    isSaved: false,
    isLiked: false,
    createdAt: "2 giờ trước",
  },
  {
    id: "post2",
    author: mockUsers.user2,
    caption:
      "Hiểu đúng về giảm cân: Không phải là đói, mà là ăn thông minh! Bằng cách chọn thực phẩm giàu protein, ít tinh bột, bạn sẽ cảm thấy no lâu hơn và không bị mệt mỏi.",
    image: "/healthy-food-nutrition.jpg",
    likes: 2156,
    comments: 234,
    isSaved: false,
    isLiked: false,
    createdAt: "5 giờ trước",
  },
  {
    id: "post3",
    author: mockUsers.user3,
    caption:
      'Huyết áp cao là "kẻ thù lặng lẽ" nếu không được kiểm soát. Tôi muốn chia sẻ 7 cách đơn giản để kiểm soát huyết áp tự nhiên mà không cần dùng quá nhiều thuốc.',
    image: "/blood-pressure.png",
    likes: 1876,
    comments: 145,
    isSaved: false,
    isLiked: false,
    createdAt: "8 giờ trước",
  },
  {
    id: "post4",
    author: mockUsers.user4,
    caption:
      "Cơm trưa hôm nay của bạn quá nhiều muối? Muối thừa không chỉ làm tăng cân mà còn gây viêm nhiễm. Dưới đây là menu 7 ngày ăn uống cân bằng, ít muối nhưng vẫn rất ngon!",
    image: "/balanced-meal-prep.jpg",
    likes: 945,
    comments: 67,
    isSaved: false,
    isLiked: false,
    createdAt: "1 ngày trước",
  },
  {
    id: "post5",
    author: mockUsers.user1,
    caption:
      "Bạn có biết rằng thiền định có thể giúp cải thiện hiệu suất lao động lên tới 30%? Tôi đã thực hành thiền 10 phút mỗi sáng trong 30 ngày và cảm thấy thay đổi tích cực.",
    image: "/harddata/post/yoga2.png",
    likes: 2345,
    comments: 189,
    isSaved: false,
    isLiked: false,
    createdAt: "1 ngày trước",
  },
  {
    id: "post6",
    author: mockUsers.user5,
    caption:
      "Khám sức khỏe định kỳ là chìa khóa phòng ngừa bệnh tật! Hôm nay tôi muốn nhắc nhở mọi người về tầm quan trọng của việc kiểm tra sức khỏe ít nhất 6 tháng/lần. Đừng đợi đến khi có triệu chứng mới đi khám nhé! 🏥💙",
    image: "/harddata/post/pexels-pixabay-40568.jpg",
    likes: 3421,
    comments: 276,
    isSaved: false,
    isLiked: false,
    createdAt: "3 giờ trước",
  },
  {
    id: "post7",
    author: mockUsers.user5,
    caption:
      "Nghiên cứu y khoa mới nhất cho thấy việc duy trì lối sống lành mạnh có thể giảm 70% nguy cơ mắc bệnh mãn tính. Hãy bắt đầu từ những thói quen nhỏ: uống đủ nước, vận động 30 phút/ngày, ngủ đủ giấc. Sức khỏe là vốn quý nhất! 💪🔬",
    image: "/harddata/post/drinkwater.png",
    likes: 4156,
    comments: 342,
    isSaved: false,
    isLiked: false,
    createdAt: "6 giờ trước",
  },
  {
    id: "post8",
    author: mockUsers.user6,
    caption:
      "Chăm sóc sức khỏe trẻ em cần sự kiên nhẫn và tình yêu thương. Là bác sĩ nhi khoa, tôi luôn tin rằng mỗi em bé đều xứng đáng có một khởi đầu tốt nhất trong cuộc sống. Cha mẹ hãy chú ý đến dinh dưỡng, tiêm chủng đầy đủ và theo dõi sự phát triển của con nhé! 👶💕",
    image: "/harddata/post/baby.png",
    likes: 2987,
    comments: 198,
    isSaved: false,
    isLiked: false,
    createdAt: "4 giờ trước",
  },
  {
    id: "post9",
    author: mockUsers.user6,
    caption:
      "Vaccine - Lá chắn bảo vệ con yêu của bạn! Nhiều phụ huynh còn băn khoăn về tiêm chủng. Hôm nay tôi muốn chia sẻ: Vaccine an toàn, hiệu quả và là cách tốt nhất để bảo vệ con khỏi các bệnh nguy hiểm. Đừng bỏ lỡ lịch tiêm của bé nhé! 💉✨",
    image: "/harddata/post/pexels-cottonbro-3952224.jpg",
    likes: 3654,
    comments: 421,
    isSaved: false,
    isLiked: false,
    createdAt: "9 giờ trước",
  },
  {
    id: "post10",
    author: mockUsers.user7,
    caption:
      "Sức khỏe tinh thần quan trọng không kém gì sức khỏe thể chất! Trong thế giới hiện đại đầy áp lực, hãy dành thời gian chăm sóc tâm hồn mình. Thiền định, viết nhật ký, nói chuyện với người thân... đều là những cách tuyệt vời để giữ tinh thần tích cực. 🧠💚",
    image: "/harddata/post/yoga.png",
    likes: 2134,
    comments: 167,
    isSaved: false,
    isLiked: false,
    createdAt: "5 giờ trước",
  },
  {
    id: "post11",
    author: mockUsers.user7,
    caption:
      "Bữa ăn lành mạnh = Cơ thể khỏe mạnh! 🥗 Hôm nay tôi muốn chia sẻ một số lựa chọn thực phẩm giàu dinh dưỡng nhưng vẫn ngon miệng. Đừng nghĩ ăn healthy là ăn nhạt nhẽo nhé! Hãy sáng tạo với salad, smoothie, và các món nướng. Let's eat smart! 🌟",
    image: "/harddata/post/pexels-shvetsa-3962285.jpg",
    likes: 1876,
    comments: 134,
    isSaved: false,
    isLiked: false,
    createdAt: "7 giờ trước",
  },
  {
    id: "post12",
    author: mockUsers.user8,
    caption:
      "Thú cưng là bạn đồng hành tuyệt vời cho sức khỏe tinh thần! 🐕❤️ Nghiên cứu cho thấy nuôi chó mèo giúp giảm stress, hạ huyết áp và tăng hormone hạnh phúc. Buddy của tôi là lý do tôi cười mỗi ngày! Hãy cho thú cưng bạn những bữa ăn dinh dưỡng và chăm sóc đầy đủ nhé! 🐾",
    image: "/harddata/post/catdog.png",
    likes: 4521,
    comments: 389,
    isSaved: false,
    isLiked: false,
    createdAt: "2 giờ trước",
  },
  {
    id: "post13",
    author: mockUsers.user8,
    caption:
      "Chăm sóc sức khỏe thú cưng cũng quan trọng như chăm sóc bản thân! 🏥🐕 Hãy đảm bảo bé cưng của bạn được tiêm phòng đầy đủ, khám định kỳ, và có chế độ ăn uống phù hợp. Một chú chó khỏe mạnh sẽ mang đến niềm vui vô tận cho gia đình bạn! 💙🐾",
    image: "/harddata/post/animalhealth.png",
    likes: 3892,
    comments: 312,
    isSaved: false,
    isLiked: false,
    createdAt: "10 giờ trước",
  },
  {
    id: "post14",
    author: mockUsers.user9,
    caption:
      "Dành thời gian với thiên nhiên là liều thuốc tuyệt vời cho tâm hồn! 🌲🐕 Mỗi buổi chiều, tôi và Max đều đi dạo trong rừng. Không khí trong lành, tiếng chim hót, và sự bầu bạn của cậu bé này khiến mọi căng thẳng tan biến. Hãy thử đi bộ ngoài trời nhé, bạn sẽ cảm thấy khác biệt! 🚶‍♂️💚",
    image: "/harddata/post/natural.png",
    likes: 2567,
    comments: 178,
    isSaved: false,
    isLiked: false,
    createdAt: "4 giờ trước",
  },
  {
    id: "post15",
    author: mockUsers.user9,
    caption:
      "Tập thể dục không cần phòng gym đắt tiền! 🏃‍♂️💪 Chạy bộ, đạp xe, hay đơn giản là đi bộ với người bạn bốn chân của bạn đều là những cách tuyệt vời để giữ dáng và tăng cường sức khỏe tim mạch. Max luôn là động lực khiến tôi vận động mỗi ngày! Bạn đã vận động hôm nay chưa? 🌟",
    image: "/harddata/post/biking.png",
    likes: 1923,
    comments: 145,
    isSaved: false,
    isLiked: false,
    createdAt: "1 ngày trước",
  },
]

export const mockComments: Record<string, Comment[]> = {
  post1: [
    {
      id: "comment1",
      author: mockUsers.user2,
      text: "Yoga thực sự rất tuyệt vời! Tôi đã bắt đầu 1 tháng trước và cảm thấy cơ thể linh hoạt hơn rất nhiều.",
      likes: 45,
      isLiked: false,
      createdAt: "1 giờ trước",
    },
    {
      id: "comment2",
      author: mockUsers.user3,
      text: "Bài viết rất hữu ích. Tôi sẽ giới thiệu cho bệnh nhân của mình về yoga.",
      likes: 32,
      isLiked: false,
      createdAt: "30 phút trước",
    },
  ],
  post2: [
    {
      id: "comment3",
      author: mockUsers.user1,
      text: "Đúng vậy! Protein là chìa khóa. Tôi ăn gà không da mỗi bữa trưa và cảm thấy rất no.",
      likes: 67,
      isLiked: false,
      createdAt: "2 giờ trước",
    },
  ],
}

export const mockFeaturedPosts: Post[] = [
  mockPosts[0],
  mockPosts[1],
  mockPosts[2],
]

export const mockSuggestedUsers: User[] = [mockUsers.user2, mockUsers.user3, mockUsers.user4]

export const mockNotifications: Notification[] = [
  {
    id: "notif1",
    type: "like",
    from: mockUsers.user2,
    content: 'đã thích bài viết của bạn: "5 bài tập yoga tuyệt vời..."',
    relatedPostId: "post1",
    isRead: false,
    createdAt: "5 phút trước",
  },
  {
    id: "notif2",
    type: "comment",
    from: mockUsers.user3,
    content: 'đã bình luận về bài viết của bạn: "Bài viết rất hữu ích..."',
    relatedPostId: "post1",
    isRead: false,
    createdAt: "30 phút trước",
  },
  {
    id: "notif3",
    type: "follow",
    from: mockUsers.user4,
    content: "đã bắt đầu theo dõi bạn",
    isRead: true,
    createdAt: "2 giờ trước",
  },
  {
    id: "notif4",
    type: "system",
    content: "Chào mừng bạn đến với Health! Hãy cập nhật hồ sơ để kết nối với mọi người.",
    isRead: true,
    createdAt: "1 ngày trước",
  },
]

export const mockReports: Report[] = [
  {
    id: "report1",
    type: "post",
    reportedBy: mockUsers.user3,
    targetId: "post2",
    targetContent: "Hiểu đúng về giảm cân: Không phải là đói, mà là ăn thông minh!...",
    targetAuthor: mockUsers.user2,
    reason: "Nội dung không chính xác về y học",
    status: "pending",
    createdAt: "1 giờ trước",
  },
  {
    id: "report2",
    type: "comment",
    reportedBy: mockUsers.user1,
    targetId: "comment3",
    targetContent: "Đúng vậy! Protein là chìa khóa...",
    targetAuthor: mockUsers.user1,
    reason: "Spam hoặc quảng cáo",
    status: "pending",
    createdAt: "3 giờ trước",
  },
  {
    id: "report3",
    type: "user",
    reportedBy: mockUsers.user4,
    targetId: "user2",
    targetContent: "Hồ sơ người dùng Linh Vy",
    targetAuthor: mockUsers.user2,
    reason: "Mạo danh chuyên gia",
    status: "resolved",
    createdAt: "1 ngày trước",
  },
  {
    id: "report4",
    type: "post",
    reportedBy: mockUsers.user2,
    targetId: "post3",
    targetContent: 'Huyết áp cao là "kẻ thù lặng lẽ"...',
    targetAuthor: mockUsers.user3,
    reason: "Nội dung vi phạm quy định cộng đồng",
    status: "rejected",
    createdAt: "2 ngày trước",
  },
]
